"""
Answers a natural-language question about a prescription using its
already-extracted medical record (the same "medical_information"
structure produced by medical_extractor.py / standardizer.py).

This is a prototype rule-based Q&A engine, matching the style of
treatment.py — simple keyword matching, no ML — and it does not
replace a doctor's advice.
"""

import re

_FREQUENCY_LABELS = {
    "1-0-0": "once a day, in the morning",
    "0-1-0": "once a day, in the afternoon",
    "0-0-1": "once a day, at night",
    "1-1-0": "twice a day, morning and afternoon",
    "1-0-1": "twice a day, morning and night",
    "0-1-1": "twice a day, afternoon and night",
    "1-1-1": "three times a day — morning, afternoon and night",
}

# What common medicines are generally used for, reused for "what is
# <medicine> for" style questions when the record itself doesn't have
# a "purpose" filled in. Mirrors the drug list in treatment.py so the
# two stay consistent.
_MEDICATION_PURPOSE = {
    "omeprazole": "reduce stomach acid and treat acid-related stomach conditions",
    "pantoprazole": "reduce stomach acid and treat acid-related digestive conditions",
    "paracetamol": "relieve pain and reduce fever",
    "ibuprofen": "relieve pain, inflammation, and fever",
    "azithromycin": "treat certain bacterial infections (it's an antibiotic)",
    "amoxicillin": "treat certain bacterial infections (it's an antibiotic)",
    "cetirizine": "relieve allergy symptoms",
    "diclofenac": "relieve pain and inflammation",
    "atorvastatin": "help lower cholesterol and reduce cardiovascular risk",
    "metformin": "help control blood glucose in type 2 diabetes",
}


def _decode_frequency(code):
    code = (code or "").strip()
    return _FREQUENCY_LABELS.get(code, code or "as directed by your doctor")


def _find_mentioned_medication(question_lower, medications):
    """Return the medication dict whose name is mentioned in the question, if any."""

    for medication in medications:
        name = str(medication.get("name", "")).strip().lower()

        if name and name in question_lower:
            return medication

    return None


def _list_medications_text(medications):
    if not medications:
        return "I couldn't find any medications listed on this prescription."

    parts = []

    for medication in medications:
        name = str(medication.get("name", "")).strip()

        if not name:
            continue

        dosage = str(medication.get("dosage", "")).strip()
        frequency = str(medication.get("frequency", "")).strip()

        piece = name

        if dosage:
            piece += f", {dosage}"

        if frequency:
            piece += f" — {_decode_frequency(frequency)}"

        parts.append(piece)

    if not parts:
        return "I couldn't find any medications listed on this prescription."

    return "Your prescribed medications are: " + "; ".join(parts) + "."


def answer_query(question, record, treatment_text=""):
    """
    `record` is the standardized/simplified medical_information dict
    used elsewhere in this project (medications, diagnoses, symptoms,
    physicians, ...). `treatment_text` is the English treatment
    advice generated by treatment.generate_treatment, if available.
    """

    if not isinstance(question, str) or not question.strip():
        return "I didn't catch a question. Could you try asking again?"

    if not isinstance(record, dict):
        record = {}

    q = question.lower().strip()

    medications = record.get("medications") or []
    diagnoses = record.get("diagnoses") or []
    symptoms = record.get("symptoms") or []
    physicians = record.get("physicians") or []

    if not isinstance(medications, list):
        medications = []

    mentioned_medication = _find_mentioned_medication(q, medications)

    # ---- Purpose of a specific / any medicine ----
    # Catches both fixed phrases ("what is it for") and the more open
    # "what is <medicine> for?" pattern, which just ends in "for".
    ends_in_for = re.search(r"\bfor\??\s*$", q) is not None

    if ends_in_for or any(phrase in q for phrase in [
        "what is this medicine for", "what is it for", "why am i taking",
        "purpose of", "used for", "what for", "what does it treat"
    ]):

        target = mentioned_medication or (medications[0] if len(medications) == 1 else None)

        if target:
            name = str(target.get("name", "")).strip()
            purpose = str(target.get("purpose", "")).strip() or _MEDICATION_PURPOSE.get(name.lower())

            if purpose:
                return f"{name} is used to {purpose}."

            return (
                f"I don't have specific information on what {name} is for. "
                "Please ask your doctor or pharmacist."
            )

        return _list_medications_text(medications)

    # ---- Dosage / how often / when to take ----
    if any(phrase in q for phrase in [
        "when should i take", "how often", "how many times",
        "dosage", "how much", "when do i take"
    ]):

        target = mentioned_medication or (medications[0] if len(medications) == 1 else None)

        if target:
            name = str(target.get("name", ""))
            frequency = str(target.get("frequency", ""))
            dosage = str(target.get("dosage", ""))

            answer = f"Take {name}"

            if dosage:
                answer += f" ({dosage})"

            answer += f", {_decode_frequency(frequency)}."

            return answer

        return _list_medications_text(medications)

    # ---- Which medicines / what tablets ----
    if any(phrase in q for phrase in [
        "what medicine", "what medication", "which medicine",
        "what tablets", "list of medic", "what are my medic"
    ]):
        return _list_medications_text(medications)

    # ---- Side effects ----
    if any(phrase in q for phrase in ["side effect", "adverse effect", "reaction"]):

        target = mentioned_medication or (medications[0] if len(medications) == 1 else None)

        if target:
            name = str(target.get("name", ""))
            effects = target.get("adverse_effects") or []

            if effects:
                return f"Possible side effects of {name} include: {', '.join(str(e) for e in effects)}."

            return (
                f"No specific side effects are recorded for {name} here. "
                "Please check with your doctor or pharmacist if you notice anything unusual."
            )

        return (
            "Please check with your doctor or pharmacist about side effects "
            "for your specific medications."
        )

    # ---- Diagnosis / what's wrong ----
    if any(phrase in q for phrase in [
        "diagnosis", "what disease", "what is wrong with me",
        "what condition", "what illness", "what do i have"
    ]):

        if diagnoses:
            return "Your diagnosis is: " + ", ".join(str(d) for d in diagnoses) + "."

        return "No diagnosis was recorded on this prescription."

    # ---- Symptoms ----
    if any(phrase in q for phrase in ["symptom", "what did i complain"]):

        if symptoms:
            return "The symptoms recorded are: " + ", ".join(str(s) for s in symptoms) + "."

        return "No symptoms were recorded on this prescription."

    # ---- Doctor ----
    if any(phrase in q for phrase in [
        "who prescribed", "which doctor", "who is my doctor", "who wrote this"
    ]):

        if physicians:
            return "This was prescribed by Dr. " + ", Dr. ".join(str(p) for p in physicians) + "."

        return "No prescribing doctor was recorded on this prescription."

    # ---- General treatment / advice ----
    if any(phrase in q for phrase in [
        "what should i do", "advice", "treatment",
        "how do i take care", "recommendation"
    ]):

        if treatment_text:
            return treatment_text

        return "Please consult a qualified healthcare professional for advice."

    # ---- Fallback: try to answer about a mentioned medicine generically ----
    if mentioned_medication:
        name = str(mentioned_medication.get("name", ""))
        dosage = str(mentioned_medication.get("dosage", ""))
        frequency = str(mentioned_medication.get("frequency", ""))

        if dosage or frequency:
            return f"{name}: {dosage}, {_decode_frequency(frequency)}."

        return f"{name} is one of your prescribed medications."

    return (
        "I'm not sure how to answer that from this prescription. "
        "You can ask about your medications, dosage, diagnosis, symptoms, "
        "or general treatment advice — or consult your doctor directly."
    )